version: "3.9"
services:
  dbs:
    build: .
    ports:
      - "8000:8000"
  dbs_filecoin:
    build: ./services/dbs_filecoin/
  # dbs_arweave:
  #   build: ./services/dbs_arweave/
  ipfs:
    image: ipfs/kubo
    network_mode: host
  ipfs-cluster:
    image: ipfs/ipfs-cluster
    network_mode: host