# Generated by Django 4.1.2 on 2022-11-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0004_remove_paymentmethod_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='wallet_address',
        ),
    ]
