# Generated by Django 4.1.2 on 2022-11-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0006_alter_quote_duration_alter_quote_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='url',
            field=models.URLField(default='https://example.com', max_length=2048),
        ),
    ]
