# Generated by Django 4.1.2 on 2022-11-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0008_alter_quote_options_alter_storage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='wallet_address',
            new_name='approveAddress',
        ),
        migrations.AddField(
            model_name='quote',
            name='quoteId',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tokenAddress',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='tokenAmount',
            field=models.BigIntegerField(null=True),
        ),
    ]
