# Generated by Django 4.1.2 on 2022-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0009_rename_wallet_address_quote_approveaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='original_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='stored_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
