# Generated by Django 4.1.2 on 2022-11-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0010_file_size_alter_file_original_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='size',
            new_name='length',
        ),
    ]
