# Generated by Django 4.1.2 on 2022-11-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0011_rename_size_file_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='chain_id',
            new_name='chainId',
        ),
        migrations.AlterField(
            model_name='acceptedtoken',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptedTokens', to='oceandbs.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentMethods', to='oceandbs.storage'),
        ),
    ]
