# Generated by Django 4.1.2 on 2022-11-24 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0016_remove_quote_upload_status_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 2, 22, 454719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
