# Generated by Django 4.1.2 on 2023-02-13 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0021_alter_paymentmethod_storage_alter_quote_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='rpcEndpointUrl',
            field=models.URLField(default='https://example.com', max_length=2048),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 15, 16, 25, 188917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 14, 46, 25, 188897, tzinfo=datetime.timezone.utc)),
        ),
    ]
