# Generated by Django 4.1.2 on 2023-04-17 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0024_alter_quote_expiration_alter_quote_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 10, 16, 53, 941734, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 9, 46, 53, 941715, tzinfo=datetime.timezone.utc)),
        ),
    ]
