# Generated by Django 4.1.2 on 2023-04-17 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0025_storage_is_active_alter_quote_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 15, 3, 38, 201038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 14, 33, 38, 200876, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.BigIntegerField(blank=True, choices=[(0, 'No such quote'), (1, 'Waiting for files to be uploaded'), (100, 'Processing payment'), (200, 'Processing payment failure modes'), (300, 'Uploading file to storage'), (400, 'Upload done'), (401, 'Upload failure modes')], default=(1, 'Waiting for files to be uploaded'), max_length=256, null=True),
        ),
    ]
