# Generated by Django 4.1.2 on 2023-04-17 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0026_alter_quote_expiration_alter_quote_nonce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 15, 55, 44, 975046, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 15, 25, 44, 975022, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'No such quote'), (1, 'Waiting for files to be uploaded'), (100, 'Processing payment'), (200, 'Processing payment failure modes'), (300, 'Uploading file to storage'), (400, 'Upload done'), (401, 'Upload failure modes')], default=(1, 'Waiting for files to be uploaded'), max_length=3, null=True),
        ),
    ]
