# Generated by Django 4.1.2 on 2023-04-17 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0028_rename_wallet_address_payment_tokenaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='rpcEndpointUrl',
            field=models.URLField(default='https://rpc-mumbai.maticvigil.com/', max_length=2048),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 17, 41, 5, 463126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 10, 17, 11, 5, 463109, tzinfo=datetime.timezone.utc)),
        ),
    ]
