# Generated by Django 4.1.2 on 2023-05-13 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0029_alter_paymentmethod_rpcendpointurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='expiration',
        ),
        migrations.AlterField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 17, 12, 19, 322583, tzinfo=datetime.timezone.utc)),
        ),
    ]
