# Generated by Django 4.1.2 on 2022-11-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymentMethod',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='chainId',
            new_name='chain_id',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='paymentMethods',
            new_name='payment_methods',
        ),
    ]
