# Generated by Django 4.1.2 on 2022-11-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0002_rename_paymentmethod_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='payment_methods',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='oceandbs.storage'),
        ),
        migrations.CreateModel(
            name='AcceptedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tokens', to='oceandbs.paymentmethod')),
            ],
        ),
    ]
