# Generated by Django 4.1.2 on 2022-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0005_remove_paymentmethod_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='upload_status',
            field=models.CharField(blank=True, choices=[('200', 'Quote exists'), ('201', 'Quote created')], max_length=256, null=True),
        ),
    ]
