# Generated by Django 4.1.2 on 2022-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0013_rename_payment_method_acceptedtoken_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[['waiting', 'Waiting for transaction'], ['done', 'Payment done'], ['refunded', 'Payment refunded']], default=['waiting', 'Waiting for transaction'], max_length=256),
        ),
    ]
