# Generated by Django 4.1.2 on 2022-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0014_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='original_url',
            new_name='public_url',
        ),
        migrations.RemoveField(
            model_name='file',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_bytes',
        ),
        migrations.RemoveField(
            model_name='file',
            name='object_content',
        ),
        migrations.RemoveField(
            model_name='file',
            name='stored_url',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
