# Generated by Django 4.1.2 on 2022-11-24 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0017_quote_expiration_quote_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 11, 22, 53, 569815, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 10, 22, 53, 569795, tzinfo=datetime.timezone.utc)),
        ),
    ]
