# Generated by Django 4.1.2 on 2022-11-24 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oceandbs', '0018_alter_quote_expiration_alter_quote_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='cid',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='public_url',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 13, 56, 34, 906043, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='nonce',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 34, 906019, tzinfo=datetime.timezone.utc)),
        ),
    ]
